var zbllMap =
{
    "VHLS": {
        'F2L 4': {
            'LBR': [
                `B L B' U' R U B U L' B' R'`,
                `B L B2 R2 B' R2 B2 R U2 R' L'`,
                `B L F L F2 L' F L F2 L2 B'`,
                `B L F U' R' F' R U2 L' U' B'`,
                `B L F' U' F2 U F L F2 L2 B'`,
                `B L F2 L F2 L2 U L U' L' B'`,
                `B L F2 L2 B' L2 F2 R U2 R' L'`,
                `B L U' F' L' U L F U L' B'`,
                `B L U' F' L' U' L F U L' B'`,
                `B L U' F' L' U2 L F U L' B'`,
                `B L U' F' U L' B' U' L F L'`,
                `B L U' L' F' U F L U L' B'`,
                `B L U' L' F2 L F U L' F B'`,
                `B L U' R U B U B' R' L' B'`,
                `B L U' R' F R F2 U F L' B'`,
                `B L U2 R' F R U F' L' U B'`,
                `B L U2 R2 B' R' B R' U2 L' B'`,
                `B L' B' L F' L' B L B' U' F`,
                `B L' B' L F' L' B L B' U2 F`,
                `B L' B' R B L B' R' F' U2 F`,
            ],
            'B': [
                `B L B' R B U L' U2 B' U2 R'`,
                `B L U L' U' F B2 R2 F' R2 B`,
                `B L U L' U' F' B2 U F U' B`,
                `B L U L' U' F' L2 F' L2 F2 B'`,
                `B L U' F U F' L' F' B' U2 F`,
                `B L2 F' L2 B' U' B L F L' B'`,
                `B U B L' B' L U' F' B' U2 F`,
                `B U B' R' F' U2 F2 U R U' F'`,
                `B U B' U R B' R F B R2 F'`,
                `B U B' U R F R2 F' B' R' B`,
                `B U B' U' F B' R' F' R2 B R'`,
                `B U B' U2 F' U F B' R B R'`,
                `B U F' U2 F U' L U' L' U' B'`,
                `B U' F' B' U2 F U' B' R B R'`,
                `B U' F' U F2 B' U R U' R' F'`,
                `B U' F2 L2 F L' U' L' U F B'`,
                `B U2 F' B' U' F U2 B' R B R'`,
                `B U2 F' B' U' L' B2 L' B2 L2 F`,
                `B U2 F' U' B L' B' L F U2 B'`,
                `B U2 F' U2 L U L' U' F U2 B'`,
            ],
            'BR': [
                `B L B' U' R U B L' U B' R'`,
                `B L F' L F L2 B' U' R U' R'`,
                `B L F' L' B' R' L F R F L'`,
                `B L F2 L F2 L2 B' U' R U2 R'`,
                `B L F2 L F2 L2 B' U2 R U' R'`,
                `B L F2 U' F U L' B' L F2 L'`,
                `B L U R U R' F' U' F L' B'`,
                `B L U' F' L' U L U F L' B'`,
                `B L U' F' U F2 U' F' U L' B'`,
                `B L U' L' B' R U R B' R2 B`,
                `B L U' L' U B' R' U R2 U' R'`,
                `B L U' L' U2 F' L U L' F B'`,
                `B L U' L' U2 L F' U F L' B'`,
                `B L U' R U L' B U B' R' B'`,
                `B L U' R' F2 R F U F L' B'`,
                `B L U2 F U F2 U F L' U2 B'`,
                `B L' B L2 U' F' U L F L2 B2`,
                `B L' B' L2 F R' F2 L F R L2`,
                `B L' B' L2 F U' R' F' R U L'`,
                `B L' B' L2 F2 U' L' U L2 F2 L2`,
            ],
            'R': [
                `B L B' U' R U B U2 L' B' R'`,
                `B L F R' L F L' F' R L' B'`,
                `B L F' L' B' U2 B L F L' B'`,
                `B L U' F' L' U2 L U F L' B'`,
                `B L U' L' B' R' U R F' U2 F`,
                `B L U' L' F' U F B' R' U R`,
                `B L U2 F' R' F R U2 F L' B'`,
                `B L' B' L U2 F' U L U L' F`,
                `B L' B' L U2 L U' F' U' F L'`,
                `B L2 F' L' F L' B' U F' U F`,
                `B L2 F' L' F' L F L' F L' B'`,
                `B L2 F' L2 B' U2 L U F U' L'`,
                `B L2 F' L2 B2 U' B L F U L'`,
                `B U B' U B' R2 F R' B R' F'`,
                `B U B2 R B R2 U R F' U2 F`,
                `B U L U' L' U2 F' U F U2 B'`,
                `B U' F' B' U2 F R' F' U' F R`,
                `B U' F' L' F' L F U L F B'`,
                `B U' F' U F B' R2 B' R' B R'`,
                `B U' F' U F B2 R' U' R U B`,
            ],
            'LR': [
                `B L B' R B U L' U' B' U R'`,
                `B L B' U R U R' U' B L' B'`,
                `B L B' U' L2 F2 L' F U F L2`,
                `B L B' U' R B U B L' B2 R'`,
                `B L F' L' B' U L U F U' L'`,
                `B L F2 L F L' F U L' U' B'`,
                `B L F2 L' F' B' U F L F2 L'`,
                `B L U L2 U2 R U' R' U2 L B'`,
                `B L U R L' B' U B R' U' B'`,
                `B L U' F U F' L' B' R U' R'`,
                `B L U' F' R' F2 R U F L' B'`,
                `B L U' F' U F2 L' B' L F' L'`,
                `B L U' F' U2 L' U' B' L F L'`,
                `B L U' F' U2 L' U' L F L' B'`,
                `B L U' L' U' B' R' U R2 U' R'`,
                `B L U2 L' U' F B' R' F' U' R`,
                `B L U2 L' U2 R B U B' R' B'`,
                `B L' B' U2 R U' R' U2 B L B'`,
                `B L' U' F' L2 U L2 F U L B'`,
                `B L2 F' L' F' U' F2 U F2 L' B'`,
            ],
            'LB': [
                `B L F B' R' F' R2 B L' B' R'`,
                `B L F R' F L F' R F' L2 B'`,
                `B L F' L F L2 B' U' R U2 R'`,
                `B L F' L F L2 B' U2 R U' R'`,
                `B L F2 B2 R2 B' L2 F2 L B2 R2`,
                `B L F2 B2 R2 B' R2 B2 L F2 L2`,
                `B L F2 B2 R2 L2 F2 L B2 R2 B'`,
                `B L F2 L B2 R2 B' L2 F2 B2 R2`,
                `B L F2 L B2 R2 B' R2 F2 B2 L2`,
                `B L F2 L B2 R2 L2 F2 B2 R2 B'`,
                `B L F2 L' B' L F' R' F' R L'`,
                `B L F2 L' F2 B2 R2 F2 R2 F2 B`,
                `B L F2 L2 B L' F2 L B' L B'`,
                `B L F2 R U2 L2 U2 R' L F2 B'`,
                `B L F2 R' F2 R2 U2 R' L' U2 B'`,
                `B L F2 R2 L' B2 L2 F2 R2 L2 B`,
                `B L U' L' B' U' R' U2 R2 U2 R'`,
                `B L U' L' U' F B' R' F' U R`,
                `B L' B L B2 L' B2 R2 B2 R2 L`,
                `B L' B L B2 R2 L F2 R2 F2 L'`,
            ],
            'L': [
                `B L F B' R2 F' R2 B U2 L' B'`,
                `B L F' L F L2 B' U' F' U F`,
                `B L F' L F L2 B' U2 F' U2 F`,
                `B L F' L F L2 U' F' U F B'`,
                `B L F' L' B' U2 B L2 F L2 B'`,
                `B L F' L' B' U2 F U F U' F'`,
                `B L F' L' B' U2 F U2 F U2 F'`,
                `B L F' U' R' F R U F L' B'`,
                `B L F2 L F2 L' F' L F L2 B'`,
                `B L U L' U' F2 L F L' F B'`,
                `B L U' F' U2 L' U' L2 F L2 B'`,
                `B L U' L' B' R' U R F' U F`,
                `B L U' L' F' B' R' U R U F`,
                `B L U2 B' R2 F R2 F' B L' B'`,
                `B L U2 F' U2 F2 U F' L' U2 B'`,
                `B L' B' R B2 L B2 R2 F R F'`,
                `B L2 F' L2 B' U2 B L F L' B'`,
                `B R U2 L U2 R' F' L F L2 B'`,
                `B U B' R' F' U2 F U F R F'`,
                `B U B' R2 F R F' U' F R F'`,
            ],
            'Dot': [
                `B L F L' B' U2 R' L F R L'`,
                `B L F' L F L2 F B' R' F' R`,
                `B L U L' U' F B2 R' F' R B`,
                `B L U' L' U F B' R' F' U R`,
                `B L' B' R B L2 U L' U B' R'`,
                `B U L U' B' R B L' U B' R'`,
                `B U' L' B L F B2 R' F' U R`,
                `B' L F U' R' U2 F' U' R L' B`,
                `B' R B R' F' U' F2 R' F' U R`,
                `B' R B U2 R U R' U' B' R2 B`,
                `B' R B2 U2 B2 R F B R F' R`,
                `B' R U R2 U B' R B R U' B`,
                `B' R U2 R F R2 F' R B' R' B2`,
                `B' U' F R' F' R2 U' R2 U2 R B`,
                `B' U' R B U B L' B R' B2 L`,
                `B' U2 B L F R U2 R2 F' R L'`,
                `F B R' F' R U' L U L' U B'`,
                `F B' R' F' R B2 U L U' L' B'`,
                `F B' R' F' U R B U L U2 L'`,
                `F B' R' F' U R U2 R' U' R B`,
            ],
        },
        'F2L 3': {
            'FBR': [
                `B L B' R2 B L' B' R2 F' U' F`,
                `B L F L' B' L F' L' F' U' F`,
                `B L F' L' B2 L U F U' L' B`,
                `B L F2 L' B' L F2 L' F' U' F`,
                `B L U L' U' L2 F2 L' F2 L' B'`,
                `B L U' L' U' B' R' U F R F'`,
                `B L U' R L' U' R' B' R' U R`,
                `B L' B' R2 B L B' R2 F' U' F`,
                `B L' F L' F L F2 L' F L2 B'`,
                `B L2 B2 U2 F B U2 F2 L2 U' F`,
                `B L2 F' L2 B' U B L2 F L2 B'`,
                `B L2 F' L2 B' U F U F U' F'`,
                `B L2 F' L2 B' U F U2 F U2 F'`,
                `B R B U' B2 U' B U' R' U B'`,
                `B R F R B2 R B2 R2 F' R' B'`,
                `B R F R' F' R2 B2 R B2 R B'`,
                `B R L B U' B' L' U' R' U B'`,
                `B R L U' L' U2 L U R' L' B'`,
                `B R2 F2 U2 F B U2 B2 R2 U' F`,
                `B R2 L2 F2 B2 R2 L2 F B U' F`,
            ],
            'BR': [
                `B L U' F' U F L' F' B' U F`,
                `B L U' R L' U' R' L U L' B'`,
                `B L' B L B2 U F R' F' U R`,
                `B L2 F' L' F L' B' U R U R'`,
                `B L2 F' L' F2 U' F2 U F L' B'`,
                `B L2 F' L2 B' L F R L' U2 R'`,
                `B L2 F' L2 B' L F' R' F2 R L'`,
                `B L2 F' L2 B' U B L F L' B'`,
                `B R B' R L' B' R' L B R' B'`,
                `B R B' U2 B R' B' U F' U' F`,
                `B U B2 R B R' F R' F' U R`,
                `B U L U' L' B' U F R' F' R`,
                `B U2 B' U2 B' U' R U R B R2`,
                `B U2 B2 R2 F R F' R2 B U' R'`,
                `B U2 F' B' U F U2 B' R B R'`,
                `B U2 F' B' U L' B2 L' B2 L2 F`,
                `B' R B R2 F' R' U R U' F R2`,
                `B' R B U B L' B2 R' B2 L B'`,
                `B' R B U B R' U2 R' U2 R B'`,
                `B' R B U B' R F R F' R B`,
            ],
            'R': [
                `B L F' U' R' F' R U F L' B'`,
                `B U2 B2 R2 F B R F' R2 U' R'`,
                `B U2 B2 R2 F R2 F' R B U R'`,
                `B U2 F' B' U F R2 F R F' R`,
                `B U2 F' U L U2 L' U2 F U2 B'`,
                `B' R B U' L' B' R B' R2 B2 L`,
                `B' R F R2 F' R' B U R U2 R'`,
                `B' R' B' R' B R2 U' R B' R2 B2`,
                `B' R' U R F' U' R' U' R F B`,
                `B' R2 B R' U B U B' R2 U2 R`,
                `B' R2 B R' U' R2 U R F' U' F`,
                `B' U' R' U R B U R' F R F'`,
                `B' U' R2 B' R2 B2 L F U F' L'`,
                `F B' R2 F' R2 F' B L' U L F`,
                `F L F2 L' U2 F' U' R' F2 R F2`,
                `F R F U F' R' F U' F U' F`,
                `F R' F' R2 U2 B U' B2 R B R2`,
                `F R' F2 R2 U L' U' R2 L F R`,
                `F R' U' F2 U F' R U2 F2 U2 F2`,
                `F U F' L' U' L F U' F2 U' F`,
            ],
            'B': [
                `B L U L' B' R' F' U' F2 R F'`,
                `B L2 F' L2 B' L F L' F' U F`,
                `B R U L U' R' L' F' B' U F`,
                `B U L U' L' U2 F' U' F U2 B'`,
                `B U2 B' U2 B' R B R2 F R F'`,
                `B U2 F' L U' F' L' F U2 F B'`,
                `B U2 F' U2 L U2 L' U2 F U2 B'`,
                `B U2 R2 B R' B2 R B' R2 U2 B'`,
                `B' R U' B U B L' B R' B2 L`,
                `B' R' F' R' B R' U' R2 F U R`,
                `B' U F' U' B U2 L' U L U F`,
                `B' U' R' U' R U F' U2 F U' B`,
                `B' U' R2 B' R2 B2 U B L' B' L`,
                `F B' R F' R F R' F2 B U' F`,
                `F B' R' F' B' R' B R' B' R2 B2`,
                `F B' R' F2 B U2 F U' B' R' B`,
                `F B' U R F' R' F U' R' F' B`,
                `F L2 U2 B L' F2 L B' U2 L2 F'`,
                `F R' F' R U R U' R' F' U' F`,
                `F R2 B' R F' R2 B R' F' U' F`,
            ],
            'F': [
                `B L F2 L' B' L U F' U' F2 L'`,
                `B L U' L' B' U' R' U2 F R F'`,
                `B L' F L' F L F2 L2 F L' B'`,
                `B R L2 U2 B L B' U2 R' L2 B'`,
                `B U B2 R F B R' F' R2 U R`,
                `B' R B U' B' R U' R2 U R2 B`,
                `B' R F R' F' R' B U F' U2 F`,
                `B' R F R' F' R' B U2 F' U F`,
                `B' R2 B U2 L' B' R' B' R B2 L`,
                `B' U F' R' F U' F' R U' F B`,
                `B' U' R B L U2 L' B' R' U B`,
                `B' U' R' U R U F' U' B U' F`,
                `F B' R B R' F2 U' F R' U R`,
                `F B' R F' R' F R' F2 B U' F`,
                `F B' R' F' R B R2 B' R' B R'`,
                `F B' R2 F' R F R F2 B U' F`,
                `F B' R2 F' R2 B R B U B' R'`,
                `F R' F R F2 U2 L F' L' U F`,
                `F R' F2 B2 U' F U B2 R2 U2 R'`,
                `F U F2 U2 R' F2 R F L' U L`,
            ],
            'FR': [
                `B L B' R B L' U B2 R B R2`,
                `B L B' R B L2 B L B2 U R'`,
                `B L F' L' B2 U L F L' U' B`,
                `B R B' U2 B R' B' U' F' U' F`,
                `B R F' U' L' U L F U R' B'`,
                `B R L F2 R' F' R F' R' L' B'`,
                `B R U L' U' B' U B R' L B'`,
                `B R2 U2 R' U2 R' F R F' R' B'`,
                `B U' B2 R' B R B' R B2 U B'`,
                `B U2 B' R B U2 B2 U' R' U B`,
                `B U2 F' B L2 B' L' F' L' F2 B'`,
                `B U2 R B2 L' B' L B' U2 R' B'`,
                `B U2 R U R' U B' U2 F' U' F`,
                `B' R B R U R' B' U' R2 U B`,
                `B' R B R' F R' F' R' F R2 F'`,
                `B' R B U L' B' R' U' B U L`,
                `B' R B U R' U' B L U L' B'`,
                `B' R B U' R U2 R2 U2 R U2 R`,
                `B' R B U2 B' R' B U R U2 R'`,
                `B' R B U2 B2 U' B R' B' U B2`,
            ],
            'FB': [
                `B L F2 L' F B2 U F2 U' F' B`,
                `B L U' F' U F L' B' R U' R'`,
                `B L U' F' U F' L' B' L F2 L'`,
                `B L U' L' B' U R U2 B' R' B`,
                `B L2 F' L2 B' L U F2 U' F' L'`,
                `B R U2 L U F U F' R' L' B'`,
                `B U L U' L' F' B' L' U L F`,
                `B U R L U R' F' U' F L' B'`,
                `B U' F' U B' U' L' U L U F`,
                `B U' L' B' R B L U B2 R' B`,
                `B U' R U' R' U2 B' U2 F' U' F`,
                `B U2 B' R B U2 B' U' B' R' B`,
                `B U2 B' R2 U R2 U' F R F' R`,
                `B' L2 U F' L' F' L F2 U' L2 B`,
                `B' R B U B2 L2 B R' B' L2 B2`,
                `B' R B U R' F R B' R' F' B`,
                `B' R B U' F' U F U B' R B`,
                `B' R B U2 B' U' B' R' B U B`,
                `B' R B U2 R' U' R' U F R F'`,
                `B' R F R' F' R U' R' U R2 B`,
            ],
            'Dot': [
                `B U L U' L' B' R B U B' R'`,
                `B' R B U' F R' F' U2 R2 U2 R`,
                `B' R B U' R' U2 R' U2 F R F'`,
                `B' U2 B U2 R B U L' B' R' L`,
                `F B' R' F' R B U2 F R' F' R`,
                `F B' R' F' U R2 U2 R2 U' R B`,
                `F R2 U F' R F U' R2 F2 U' F`,
                `F R2 U F' R' F U' R2 F2 U' F`,
                `F' B L F2 U2 F L' F' U2 F' B'`,
                `F' L F' L' F2 R2 B' R' B U' R'`,
                `F' L F' L' F2 U2 F' L F' L' F2`,
                `F' L' B' U2 B U' L F R U R'`,
                `F' L' U L U L F' L' F U2 F`,
                `F' L' U2 B L' B' L2 F R U R'`,
                `F' L' U2 L F R U B' R B R2`,
                `F' L' U2 L F R U2 R2 F R F'`,
                `F' L' U2 L2 F2 L2 B L' B' L2 F'`,
                `F' L2 B L2 U L' U' B' L U F`,
                `F' U B L' B' U2 B L B' U2 F`,
                `F' U F R B L U L' U B' R'`,
            ],
        },
        'F2L 2': {
            'FLR': [
                `B L F L' B' L F R' F2 R L'`,
                `B L F L' B' L F' R L' U R'`,
                `B L F L' B' L F' R L' U2 R'`,
                `B L F U' F2 U L' B' L F L'`,
                `B L F' L' B' L F R L' U2 R'`,
                `B L F' L' B' L F' R' F2 R L'`,
                `B L F2 B' R' F2 R2 B L' B' R'`,
                `B L F2 L F2 L2 B' U F' U F`,
                `B L F2 L' B' L F2 R L' U R'`,
                `B L F2 L' B' L F2 R L' U2 R'`,
                `B L F2 L' B' R' F2 R L' U2 L`,
                `B L F2 L' F U2 F' B' R2 F2 R2`,
                `B L F2 L' F2 B' R L' U2 R' L`,
                `B L U' F' R' F R F U L' B'`,
                `B L U' F' R' F' R F U L' B'`,
                `B L U' F' R' F2 R F U L' B'`,
                `B L U' L' U2 B' R' U R2 U R'`,
                `B L' B' L2 F2 L F2 L2 F' U2 F`,
                `B L' B' R2 B' R' B R' B L B'`,
                `B L' B' R2 B2 L B2 R2 F' U2 F`,
            ],
            'FL': [
                `B L F L F' L' F L F2 L2 B'`,
                `B L F2 L F2 L' F2 L F2 L2 B'`,
                `B L F2 L2 B' R' L2 F2 R U2 L'`,
                `B L' B L' F2 L B' L2 F2 L' B'`,
                `B L' B' L U2 L U2 L' F' U2 F`,
                `B L' B' R B2 L B2 R' F' U2 F`,
                `B L' B' R U' B U L B' U R'`,
                `B L2 F L2 B' U2 B L F2 L' B'`,
                `B R U L U' R' L' F' B' U2 F`,
                `B R U2 L U2 R' F2 L F2 L2 B'`,
                `B U L U' F2 L F L' F L' B'`,
                `B U L U' L' B2 R2 F R2 F' B`,
                `B U L U' L' F2 L2 F L2 F B'`,
                `B U L U' L' U' F' U B' U2 F`,
                `B U L U2 R U' R' U' L' U' B'`,
                `B U L U2 R U2 L' U R' U2 B'`,
                `B U R B2 R B2 R' U R' U2 B'`,
                `B U' F' U B' U F U R U' R'`,
                `B U' F' U B' U F U2 R U2 R'`,
                `B U' F' U B' U L' U2 L U F`,
            ],
            'LR': [
                `B L' B' U F' U F U2 B L B'`,
                `B L' B' U R U' R B L B' R2`,
                `B L' B' U R U2 B U L B' R'`,
                `B R B' U' B U L U' R' L' B'`,
                `B R U2 B2 U B U' B2 R' U2 B'`,
                `B U B' R' F' U' F2 R F2 U2 F`,
                `B U B' U' B' R B R' F' U F`,
                `B U B' U' F' B' R B R' U F`,
                `B U B2 R B2 U' B' U' R2 U2 R`,
                `B U L F' L' U' B L F L' B2`,
                `B U L U' F' L' B' U2 L F L'`,
                `B U L U' L' B2 R' F R F' B`,
                `B U L U2 L F2 L' F2 L' U B'`,
                `B U L U2 R U2 L' U2 R' U B'`,
                `B U R B2 R B2 R' U2 R' U B'`,
                `B U' F' U B' L' B' U' B L F`,
                `B U' F' U B' U F U R U2 R'`,
                `B U' F' U F B' R B U' B' R'`,
                `B U' F' U L' B' U' B L F B'`,
                `B U' F2 B L F U L' U' F B2`,
            ],
            'FR': [
                `B L F U' F2 U F U L' U' B'`,
                `B L F' L F L2 B' U' F' U' F`,
                `B L F' U' F U L' B' R U2 R'`,
                `B L F' U' F' R' F2 R U L' B'`,
                `B L' U L U2 R' F R U F' B'`,
                `B L2 B' U' R U B L2 U2 B' R'`,
                `B L2 F' L2 B' R' L F' R F L'`,
                `B R B' U2 B U L U' R' L' B'`,
                `B R U2 B L' B L B2 R' U2 B'`,
                `B U B' R' F' U' F R F' U2 F`,
                `B U L' B L B' U2 F' U F B'`,
                `B U' F' L' B' U' B L F U2 B'`,
                `B U' F' U B' U F R' F R F'`,
                `B U' F' U B' U F U R U R'`,
                `B U' F' U B' U' L' U2 L U F`,
                `B U' F' U F B2 R U' R' U B`,
                `B U' F' U F R B' U' B R' B'`,
                `B U' F' U L U L2 U' L F B'`,
                `B U' F' U' F B' R U' R2 U R`,
                `B U' R U R' U2 L U' L' U' B'`,
            ],
            'R': [
                `B L U L' B' U' B' R B U' R'`,
                `B L' B' R B L2 U L' B' U2 R'`,
                `B R U2 B' R' U B U B U' B2`,
                `B U B' U' B' R B2 U2 B' U' R'`,
                `B U2 B' U2 L' B' R B L U2 R'`,
                `B' R B U' R' F' U2 R' U2 R F`,
                `B' R B U2 R' U' R' U R2 U R'`,
                `B' R F B' R F' R' B2 R U2 R'`,
                `B' R F R F' R' B U R U R'`,
                `B' R' F R F B2 L F L' F B'`,
                `B' R2 U' R U B L' B' R2 B L`,
                `B' U' L U' R U R2 L' U R B`,
                `B' U' R F U R' U' F' U R' B`,
                `B' U' R U R' B2 U L U' L' B'`,
                `B' U' R U R2 U R B L U' L'`,
                `B' U' R U2 R2 U R2 U2 R' U B`,
                `B' U2 F' R' F U2 R' F' R2 F B`,
                `B2 L' B R' B R' B' R B' L B2`,
                `B2 L2 F' B' U L U' F B L2 B2`,
                `B2 R U R U R' U' R' B R' B`,
            ],
            'L': [
                `B L F B' U2 F B L2 F2 L B'`,
                `B L F U2 F2 U2 F2 U2 F' L' B'`,
                `B L F' U2 F2 U2 F2 U2 F L' B'`,
                `B L F2 L B2 R' F2 R B2 L2 B'`,
                `B L' F2 L2 F' B' U2 F' B L' B'`,
                `B R L2 B2 U2 L2 U2 B2 R' L2 B'`,
                `B R U B2 U2 B2 U2 B2 U' R' B'`,
                `B R U' B2 U2 B2 U2 B2 U R' B'`,
                `B R U2 R' B2 U2 L' B2 L U2 B`,
                `B R2 L U2 F2 R2 F2 U2 R2 L' B'`,
                `B U B2 R B2 U2 B' U' R2 U2 R`,
                `B U L U L' U2 R U2 R' U2 B'`,
                `B U L U R' F2 R F2 L' U2 B'`,
                `B U L U' L' B' R2 B' R' B R'`,
                `B U' B' U R U2 R F R F' R`,
                `B U' B' U' R2 U2 R U2 F R2 F'`,
                `B U' R U B U B2 U' B R' B'`,
                `B' L2 B2 U2 F2 L' F2 U2 B2 L2 B`,
                `B' L2 F2 U2 B2 L' B2 U2 F2 L2 B`,
                `B' R' U R F R' F' U2 R U B`,
            ],
            'F': [
                `B L F2 U' F2 U L' B' L F2 L'`,
                `B L U R L' B' U2 B R' U' B'`,
                `B L U' F2 U' F2 U F2 U2 L' B'`,
                `B L U' L' U' B' R' U R2 U R'`,
                `B R U L U' R' F2 L F2 L2 B'`,
                `B R U R B' R' U B R' U' B'`,
                `B U L U' L' B' U2 F R' F' R`,
                `B U L U' L2 B' L2 F2 L F2 L2`,
                `B U L U' L2 B' R2 B2 L B2 R2`,
                `B U L U' R2 L2 B2 L B2 R2 B'`,
                `B U L' B2 R B2 L U B2 R' B`,
                `B U R' U2 R U2 R U B2 R' B`,
                `B U' B' U R U2 B' R' B2 U2 B'`,
                `B U2 B' U R U' R F R F' R`,
                `B U2 B' U2 B' U' R U B U2 R'`,
                `B' R' U R F U R' U' F' R B`,
                `B' R2 F R F' R2 B U B' R' B`,
                `B' U' R U B' R' B2 U' L U' L'`,
                `B' U' R U B2 L' B2 R' B2 L B'`,
                `B' U' R U B2 R' U2 R' U2 R B'`,
            ],
            'Dot': [
                `B L F2 U2 B' R2 F R2 B L' B'`,
                `B L F2 U2 F' U2 F U2 F L' B'`,
                `B U2 B' R' B U2 F B2 R' F' B`,
                `B U2 B2 R' B2 U2 F B2 R F' B`,
                `B' R F R2 F' R' B U R U R'`,
                `B' R' B U2 F L2 B' R' B L2 F'`,
                `F B U2 F L F' U2 F2 L' F B'`,
                `F R' F2 U' B U2 F B' R2 U R`,
                `F U2 F U2 R' F R2 U2 R2 F2 R`,
                `F' B L' B' U2 L F U L U' L'`,
                `F' B L' B' U2 L F U2 L U2 L'`,
                `F' L F2 L' F2 U2 R' F R2 U2 R'`,
                `F' L' U2 L2 F L' U2 F2 R' F2 R`,
                `F' L2 U' B U L U' B' L U' F`,
                `F' U F U' R U2 B U2 B' U2 R'`,
                `F' U F2 R' F' R2 U R' F' U' F`,
                `F' U L' U2 L U2 F U' R U2 R'`,
                `F' U L' U2 L U2 F U2 R U' R'`,
                `F' U' F R U B' R B R' U2 R'`,
                `F' U' F2 U R' U' F' U R2 U R'`,
            ],
        },
        'F2L 1': {
            'FLB': [
                `B L B' R B U L' B2 R B R2`,
                `B L B' U' R U B L' B' U2 R'`,
                `B L B2 R U R B' R2 B2 U' L'`,
                `B L F U' F' R U' R' U2 L' B'`,
                `B L F' L' B' L F R L' U' R'`,
                `B L F2 L' B' L F2 R L' U' R'`,
                `B L F2 L' B' L U F2 U' F2 L'`,
                `B L U' F' U L F' L' F2 L' B'`,
                `B L U' L' B' U R U B' R' B`,
                `B L U' L' F B' R2 F' R U R`,
                `B L U' L' U' F' L U L' F B'`,
                `B L U' L' U' L F' U F L' B'`,
                `B L U' L' U2 B' R U' R2 U2 R`,
                `B L U' L' U2 B' R' U R2 U' R'`,
                `B L U' L' U2 B' R' U R2 U2 R'`,
                `B L U' R L' U2 R' B' R' U R`,
                `B L U2 R U R' F' U F L' B'`,
                `B L' B L B2 U2 R U2 B' R' B`,
                `B L' B R B' L B' U' B2 R' B2`,
                `B L' B' R B L2 U' L' U2 B' R'`,
            ],
            'L': [
                `B L U L' U' B2 U' R U R' B`,
                `B L U' F2 R' L F2 R L2 U' B'`,
                `B L U' L' U' B' R U' R2 U2 R`,
                `B L U' L' U' B' R' U R2 U2 R'`,
                `B L2 F' L' F U' F' U F L' B'`,
                `B R B' U B' R' B U B2 U' B2`,
                `B R B' U2 B R' L U L' U' B'`,
                `B R L U' L' U L U R' L' B'`,
                `B R' F' U' F U R2 U2 R' U2 B'`,
                `B U L U' L' B' R B U2 B' R'`,
                `B U R U' R' U' R' F R F' B'`,
                `B U2 B2 R B2 U2 B' U' B' R' B`,
                `B U2 F2 L2 U' L U L2 F2 U2 B'`,
                `B U2 L F2 R' F2 R U' L' U' B'`,
                `B U2 R U2 R' U2 L U' L' U' B'`,
                `B' R B U B' R' B U' R U2 R'`,
                `B' R B U B' R' B U2 R U' R'`,
                `B' R B U' B' R2 F R' F' R2 B`,
                `B' R B U' B2 R2 F R' F' R2 B2`,
                `B' R B U' R' U' R' F' U F R`,
            ],
            'B': [
                `B L F U' F' U F2 L F2 L2 B'`,
                `B L U' R L' U2 R' L U L' B'`,
                `B L U2 F2 U' F2 U F2 U L' B'`,
                `B L' B' U2 R U2 R' U2 B L B'`,
                `B L2 F' L' F L' F B' R' F' R`,
                `B R B' R L' B2 R' L B R' B'`,
                `B R B' U' B R' B' R' F R F'`,
                `B U' R' F R F' U2 L U' L' B'`,
                `B U2 L U' R U2 R' U L' U2 B'`,
                `B U2 R U2 R2 U' F' U F R B'`,
                `B' R B U L' B' R B' R2 B2 L`,
                `B' R B U2 B' R' B U' R U2 R'`,
                `B' R B U2 B' R' B U2 R U' R'`,
                `B' R B2 U2 B' R B' R2 B2 U2 B'`,
                `B' R B2 U2 B' R F R2 F2 U2 F`,
                `B' R U' R' U B2 U L U' L' B'`,
                `B' R U' R2 L U' R U L' U B`,
                `B' R U' R2 U2 R B U L U2 L'`,
                `B' R U' R2 U2 R U2 R' U' R B`,
                `B' R' B' R2 F' B U2 F2 R F' B`,
            ],
            'LB': [
                `B L B' R2 B L' B' R F R F'`,
                `B L F U' F' U L' F' B' U2 F`,
                `B L U F' L' U' B L F L' B2`,
                `B L U' F2 R' F2 R U2 L' U' B'`,
                `B L U' L' B' R' F' U F2 R F'`,
                `B L U' L' U2 B' R' U F R F'`,
                `B L' B' R2 B L B' R F R F'`,
                `B L' U' F' L2 U' L2 F U L B'`,
                `B L2 F' L' F L' B' U' F' U F`,
                `B L2 F' L' F L' B' U2 F' U2 F`,
                `B L2 F' L' F L' U' F' U F B'`,
                `B L2 F2 L2 F' B' U F L F2 L'`,
                `B R B U' B2 U2 B U' R' U B'`,
                `B R B' U' B R' L U L' U' B'`,
                `B R U2 B' L' B' L B U2 R' B'`,
                `B R' L F R L' B L F' L' B2`,
                `B U B' R' U2 R U R2 F R2 F'`,
                `B U B' U' B' R' F R' B R2 F'`,
                `B U L' B L B' U' F' B' U2 F`,
                `B U' B' R' L U F U' R F' L'`,
            ],
            'FB': [
                `B L B' R B U2 L' U' B' U' R'`,
                `B L U L U' F' U' F U L2 B'`,
                `B L U' F R' F' R U2 L' U' B'`,
                `B L U' L' F B' R' F2 U F R`,
                `B L U2 F' U F2 U F' L' U2 B'`,
                `B L U2 R U2 B U B' R' L' B'`,
                `B L' U R U' B L B' R' U' B'`,
                `B L' U2 R U R' U2 L2 U' L' B'`,
                `B R B U' B' L' B2 L B2 R' B'`,
                `B R B U' B' R' U2 L U2 L' B'`,
                `B R B' U' B R' U L U' L' B'`,
                `B R' B' U' F U B R B' U' F'`,
                `B R2 U' L U R' U2 L' U R' B'`,
                `B U B L' B' L U2 F' U F B'`,
                `B U B' R' F' L' U' L F2 R F'`,
                `B U B' R' F' U' F2 R F2 U F`,
                `B U B' U R2 F R2 F' R U2 R'`,
                `B U B' U' B' R B R' F' U2 F`,
                `B U B' U' B' R' F R2 B R' F'`,
                `B U B' U' R' F B' R' B R F'`,
            ],
            'F': [
                `B L B' R2 B L' B2 R' B U' R'`,
                `B L F' U F R L' U' R' U' B'`,
                `B L U2 L' U2 R2 B2 R' B2 R' B'`,
                `B L U2 R U2 L2 B2 L B2 R' B'`,
                `B L' B L B2 U R U' R2 U2 R`,
                `B L' B L B2 U R' U R2 U2 R'`,
                `B L' B' U2 F2 L F2 U2 L2 U2 L'`,
                `B L2 F L' F' L' B' U2 L F2 L'`,
                `B R B' U B R' U L U' L' B'`,
                `B R B' U2 B R' B' R' F R F'`,
                `B R B' U2 B' R' B U B2 U' B2`,
                `B R B2 L' B2 L2 U2 R' U2 L' B'`,
                `B R B2 R B2 R2 U2 L U2 L' B'`,
                `B R B2 U' R' U B U B2 U' B2`,
                `B R U B' R' U2 R B U' R' B'`,
                `B R U' B2 U' B2 U B2 U R' B'`,
                `B R' B2 L U2 F2 R2 F2 L' U2 B`,
                `B U B' R' B' R2 B U R2 U2 R'`,
                `B U B' R' F' U2 F U R2 U2 R'`,
                `B U B' U R2 F R F' R2 U2 R'`,
            ],
            'FL': [
                `B L B' U R U' R' U' B L' B'`,
                `B L F' L' U L U' L F L2 B'`,
                `B L U' L' U B' R' U F R F'`,
                `B L U2 R U2 L' B U B' R' B'`,
                `B L' B' R B2 L B' U' B' U2 R'`,
                `B L2 B2 R' F2 R' B' L2 F2 B2 R2`,
                `B L2 B2 R' F2 R' B' R2 F2 B2 L2`,
                `B L2 B2 R' F2 R' L2 F2 B2 R2 B'`,
                `B L2 F' L' F L' B' U F' U2 F`,
                `B L2 F' L' F L' B' U2 F' U F`,
                `B L2 F2 L' F2 L' B' U F' U2 F`,
                `B L2 F2 L' F2 L' B' U2 F' U F`,
                `B R B R B' R' U' B' R' U B'`,
                `B R B U' B2 U B U' R' U B'`,
                `B R B' U B R' B' R' F R F'`,
                `B R B' U B R' L U L' U' B'`,
                `B R B' U' B' R' B U B2 U' B2`,
                `B R B' U2 B R' U L U' L' B'`,
                `B R B2 R B2 R' B U B' R' B'`,
                `B R B2 U' B' R' B U B' U' B2`,
            ],
            'Dot': [
                `B U F' U L U' L2 U' L F B'`,
                `B U' L U' L' U R' F R F' B'`,
                `B U2 F2 L F2 U2 F' L' B' U' F`,
                `B' R B R' U' R' F U R U' F'`,
                `B' R B R' U' R' F' U F2 R F'`,
                `B' R U' B' R' B2 U B L' B' L`,
                `B' R' B U2 F R' F' R B' R' B`,
                `B' R' B' U2 F B' R2 B2 R F' B`,
                `B' R' B2 U2 F B' R2 B' R F' B`,
                `B' R' F B2 U2 B2 R B2 U2 F' B'`,
                `B' R' F B2 U2 B2 R' F B R2 F2`,
                `B' R' F R F' B2 U L U' L' B'`,
                `B' R' F R F2 B U' F R U2 R'`,
                `B' R' F U R B L U' L' U' F'`,
                `B' R' F' B U B' U F U' R' B`,
                `B' R' F' U F2 R F' B L U' L'`,
                `B' R' F' U2 F2 R F2 U2 B U' F`,
                `B' R' L U F U2 R U F' L' B`,
                `B' R' U R U2 R' U' F R F' B`,
                `B' R' U' R U B U' R' F R F'`,
            ],
        },
    },
    // "Pair": {
        
    // },
    // "Split": {
        
    // },
    // "Inserted Corner": {
        
    // },
    // "Inserted Edge": {
        
    // },
    // "Inserted Both": {
        
    // },
}