let keyBoardMappings = {
    defaultMapping: ['', "S'", '', 'M', 'M', '', 'M', 'M', '', 'S', '', '',
"z'", 'B', "L'", 'l', 'x', 'x', 'r', 'R', "B'", 'z', '', '', '',
"y'", "D'", 'L', "U'", "F'", 'F', 'U', "R'", 'D', 'y', '',
"d'", "M'", "l'", "x'", "x'", '', "r'", "M'", 'd', 'd',
'', '', '', '', '', '', '', '', '', '', '', '', '', '', ''],
    trainyuMapping: ['', '', '', '', '', '', '', '', '', '', '', '', 
'', 'B', "L'", "l'", 'x', '', 'r', 'R', "B'", '', "M'", '', 'M', 
"y'", 'D', 'L', "U'", "F'", 'F', 'U', "R'", "D'", 'y', 'M', 
'', 'E', '', 'l', "x'", "r'", '', '', "E'", '', 
'', '', '', '', '', '', '', '', '', '', '', '', '', '', ''],
    cstimerMapping: ['', '', '', '', 'M', 'M', '', '', '', '', '', '', 
"z'", 'B', "L'", "l'", 'x', 'x', 'r', 'R', "B'", 'z', '', '', '', 
"y'", 'D', 'L', "U'", "F'", 'F', 'U', "R'", "D'", 'y', '', 
'd', "M'", "u'", 'l', "x'", "x'", "r'", 'u', "M'", "d'", 
'', '', '', '', '', '', '', '', '', '', '', '', '', '', '']
}

let keymap = {
    // code of key: move it applies
    // loadKeymap() populates this
    "Digit1": ["1", ""],
    "Digit2": ["2", ""],
    "Digit3": ["3", ""],
    "Digit4": ["4", ""],
    "Digit5": ["5", "M"],
    "Digit6": ["6", "M"],
    "Digit7": ["7", ""],
    "Digit8": ["8", ""],
    "Digit9": ["9", ""],
    "Digit0": ["0", ""],
    "Minus": ["-", ""],
    "Equal": ["=", ""],

    "KeyQ": ["Q", "z'"],
    "KeyW": ["W", "B"],
    "KeyE": ["E", "L'"],
    "KeyR": ["R", "l'"],
    "KeyT": ["T", "x"],
    "KeyY": ["Y", "x"],
    "KeyU": ["U", "r"],
    "KeyI": ["I", "R"],
    "KeyO": ["O", "B'"],
    "KeyP": ["P", "z"],
    "BracketLeft": ["[", ""],
    "BracketRight": ["]", ""],
    "Backslash": ["\\", ""],

    "KeyA": ["A", "y'"],
    "KeyS": ["S", "D"],
    "KeyD": ["D", "L"],
    "KeyF": ["F", "U'"],
    "KeyG": ["G", "F'"],
    "KeyH": ["H", "F"],
    "KeyJ": ["J", "U"],
    "KeyK": ["K", "R'"],
    "KeyL": ["L", "D'"],
    "Semicolon": [";", "y"],
    "Quote": ["\'", ""],

    "KeyZ": ["Z", "d"],
    "KeyX": ["X", "M'"],
    "KeyC": ["C", "u'"],
    "KeyV": ["V", "l"],
    "KeyB": ["B", "x'"],
    "KeyN": ["N", "x'"],
    "KeyM": ["M", "r'"],
    "Comma": [",", "u"],
    "Period": [".", "M'"],
    "Slash": ["/", "d'"],

    "Numpad7": ["7", ""],
    "Numpad4": ["4", ""],
    "Numpad1": ["3", ""],
    "NumpadDivide": ["/", ""],
    "Numpad8": ["8", ""],
    "Numpad5": ["5", ""],
    "Numpad2": ["1", ""],
    "NumpadMultiply": ["*", ""],
    "Numpad9": ["9", ""],
    "Numpad6": ["6", ""],
    "Numpad3": ["2", ""],
    "NumpadSubtract": ["-", ""],
    "NumpadAdd": ["+", ""],
    "Numpad0": ["0", ""],
    "NumpadDecimal": [".", ""],
}

export { keyBoardMappings, keymap }