
let blankMap = ["", "", "", "", "", "", "", "", "", "", "", "",
    "", "", "", "", "", "", "", "", "", "", "", "", "",
    "", "", "", "", "", "", "", "", "", "", "",
    "", "", "", "", "", "", "", "", "", "",
    "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""]

let keyBoardMappings = [
    // [ title, description, scheme, scheme when shift held ]
    {
        title: "default scheme",
        desc: "the control scheme Eduardo Mazuera (me!) uses to train, and the default scheme",
        map: ["", "S'", "S'", "M", "M", "", "M", "M", "", "S", "", "",
            "z'", "B", "L'", "l'", "x", "x", "r", "R", "B'", "z", "", "", "",
            "y'", "D", "L", "U'", "F'", "F", "U", "R'", "D'", "y", "",
            "d'", "M'", "l", "l", "x'", "r'", "r'", "M'", "d", "d",
            "", "y'", "", "", "x", "", "x'", "", "", "y", "", "", "", "", ""],
        shiftMap: ["", "", "", "", "", "", "", "", "", "", "", "",
        "", "", "", "", "", "", "", "", "", "", "", "", "",
        "", "", "", "", "", "", "", "", "", "", "",
        "", "", "", "", "", "", "", "", "", "",
        "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
    },
    {
        title: "Trainyu scheme",
        desc: "same virtual cube controls as in Tao Yu's alg trainer",
        map: ["", "", "", "", "", "", "", "", "", "", "", "",
            "", "B", "L'", "l'", "x", "", "r", "R", "B'", "", "M'", "", "M",
            "y'", "D", "L", "U'", "F'", "F", "U", "R'", "D'", "y", "M",
            "", "E", "", "l", "x'", "r'", "", "", "E'", "",
            "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        shiftMap: ["", "", "", "", "", "", "", "", "", "", "", "",
        "", "", "", "", "", "", "", "", "", "", "", "", "",
        "", "", "", "", "", "S'", "S", "", "", "", "",
        "", "", "", "", "", "", "", "", "", "",
        "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
    },
    {
        title: "CSTimer scheme",
        desc: "same virtual cube controls as on CSTimer (and apparently the standard)",
        map: ["", "", "", "", "M", "M", "", "", "", "", "", "",
            "z'", "B", "L'", "l'", "x", "x", "r", "R", "B'", "z", "", "", "",
            "y'", "D", "L", "U'", "F'", "F", "U", "R'", "D'", "y", "",
            "d", "M'", "u'", "l", "x'", "x'", "r'", "u", "M'", "d'",
            "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        shiftMap: ["", "", "", "", "", "", "", "", "", "", "", "",
        "", "", "", "", "", "", "", "", "", "", "", "", "",
        "", "", "", "", "", "", "", "", "", "", "",
        "", "", "", "", "", "", "", "", "", "",
        "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
    },
    {
        title: "experimental OH scheme",
        desc: "a test mapping that uses keys that naturally follow OH moves. Left Hand solvers place your fingers on S D F G and your thumb on V/B, and Right Hand solvers rest your fingers on H J K L, with thumb on V/B." +
            "Holding Shift (with your non OH hand) is akin to doing table abuse and the only way to do M moves",
        map: ["", "y'", "", "y", "S", "S'", "y'", "", "y", "", "", "",
            "R", "r", "", "u", "U", "U'", "u'", "", "l'", "L'", "", "", "",
            "R'", "r'", "D", "u'", "U'", "U", "u", "D'", "l", "L", "",
            "", "", "D'", "", "F", "F'", "", "D", "", "",
            "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        shiftMap: ["", "", "", "", "S", "S'", "", "", "", "", "", "",
        "M'", "M'", "", "E'", "U", "U'", "E", "", "M'", "M'", "", "", "",
        "M", "M", "", "E", "U'", "U", "E'", "", "M", "M", "",
        "", "", "", "", "", "", "", "", "", "",
        "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
    },
    {
        title: "old OH testing scheme",
        desc: "same as the other Oh scheme but before i tried testing it :skull: bad but I might polish this later as its a different ideology as the other OH mapping. Right Hand OH rests fingers on Q W E R; Left Hand OH rests at Y U I O",
        map: ["", "", "r", "M'", "U", "U'", "M'", "l'", "L", "", "", "",
            "", "", "D'", "M'", "U'", "U", "M'", "D", "L'", "", "", "", "",
            "R", "r", "D", "", "", "", "", "D'", "l", "", "",
            "R'", "r'", "", "F'", "F", "F'", "F", "", "M", "",
            "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        shiftMap: ["", "", "", "", "", "", "", "", "", "", "", "",
        "", "", "", "", "", "", "", "", "", "", "", "", "",
        "", "", "", "", "", "", "", "", "", "", "",
        "", "", "", "", "", "", "", "", "", "",
        "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
    }
]

let keymap = {
    // code of key: move it applies
    // loadKeymap() populates this
    "Digit1": ["1", "", ""],
    "Digit2": ["2", "", ""],
    "Digit3": ["3", "", ""],
    "Digit4": ["4", "", ""],
    "Digit5": ["5", "", ""],
    "Digit6": ["6", "", ""],
    "Digit7": ["7", "", ""],
    "Digit8": ["8", "", ""],
    "Digit9": ["9", "", ""],
    "Digit0": ["0", "", ""],
    "Minus": ["-", "", ""],
    "Equal": ["=", "", ""],

    "KeyQ": ["Q", "", ""],
    "KeyW": ["W", "", ""],
    "KeyE": ["E", "", ""],
    "KeyR": ["R", "", ""],
    "KeyT": ["T", "", ""],
    "KeyY": ["Y", "", ""],
    "KeyU": ["U", "", ""],
    "KeyI": ["I", "", ""],
    "KeyO": ["O", "", ""],
    "KeyP": ["P", "", ""],
    "BracketLeft": ["[", "", ""],
    "BracketRight": ["]", "", ""],
    "Backslash": ["\\", "", ""],

    "KeyA": ["A", "", ""],
    "KeyS": ["S", "", ""],
    "KeyD": ["D", "", ""],
    "KeyF": ["F", "", ""],
    "KeyG": ["G", "", ""],
    "KeyH": ["H", "", ""],
    "KeyJ": ["J", "", ""],
    "KeyK": ["K", "", ""],
    "KeyL": ["L", "", ""],
    "Semicolon": [";", "", ""],
    "Quote": ["\'", "", ""],

    "KeyZ": ["Z", "", ""],
    "KeyX": ["X", "", ""],
    "KeyC": ["C", "", ""],
    "KeyV": ["V", "", ""],
    "KeyB": ["B", "", ""],
    "KeyN": ["N", "", ""],
    "KeyM": ["M", "", ""],
    "Comma": [",", "", ""],
    "Period": [".", "", ""],
    "Slash": ["/", "", ""],

    "Numpad7": ["7", "", ""],
    "Numpad4": ["4", "", ""],
    "Numpad1": ["3", "", ""],
    "NumpadDivide": ["/", "", ""],
    "Numpad8": ["8", "", ""],
    "Numpad5": ["5", "", ""],
    "Numpad2": ["1", "", ""],
    "NumpadMultiply": ["*", "", ""],
    "Numpad9": ["9", "", ""],
    "Numpad6": ["6", "", ""],
    "Numpad3": ["2", "", ""],
    "NumpadSubtract": ["-", "", ""],
    "NumpadAdd": ["+", "", ""],
    "Numpad0": ["0", "", ""],
    "NumpadDecimal": [".", "", ""],
}

export { keyBoardMappings, keymap }