var llmap = [
    `U R' U' R U' R' U' L' U' L R U2 L' U' L`,
    `R2 U2 R' U R U' R U2 R U L' U R U' L`,
    `R2 F2 R U2 R U2 R' F2 R U' R' U R`,
    `U R2 U R2 U R2 U' R D R' U' R D' R`,
    `U' R U2 R' U2 R U' R' U L' U R U' L U' R'`,
    `U l' U' L U R U' r' F`,
    `R' U2 R F U' R' U R U F' R' U R`,
    `U' R' U' R U R' U R L' U R' U' R L`,
    `U F U R U2 R' U R U R' F'`,
    `U r' F2 r U2 r U' r' U' r' F r F`,
    `x' M' U' R U L' U' R' U' R U R' U R`,
    `U' R' U R U R' U' R' D' R U2 R' D R U R`,
    `L2 F2 L' U2 L' U2 L F2 L' U L U' L'`,
    `R D' R' U R2 U' R2 U' R2 U2 R' D R'`,
    `U' L U L' U L U R U L' R' U2 R U R'`,
    `U2 R2 U2 R U' R' U R' U2 R' U' L U' R' U L'`,
    `U' r U R' U' r' F R F'`,
    `U' R' U2 R U2 R' U R U' L U' R' U L' U R`,
    `U2 R U2 R' B' U R U' R' U' B R U' R'`,
    `U2 x' D R U' R' U R' U' D R' U R D2 x`,
    `U' R U2' R' U2' R' F R U R U' R' F'`,
    `U' F' U' r' F2 r U' L' U' L F`,
    `U' R U' R' U' R U R D R' U2 R D' R' U' R'`,
    `U R' U' R U R' U' R2 D R' U2 R D' R' U R' U R`,
    `R' U R U2 L' R' U R U' L`,
    `L' R U R U' L U R2 U R U2 R'`,
    `U2 R U' R' U2 L R U' R' U L'`,
    `U R' F R' F' R2 U' R' U' F' U' F R`,
    `F R U' R' U' R U2 R' U' F' R' U' R U' R' U2 R`,
    `R2' U R U' R2' U R U2' L' R U R U' R2 r x'`,
    `U2 r U' r U2 R' F R U2 r2 F`,
    `R U R' U' R' U L' U2 R U' R' U2 L R2 U' R'`,
    `R U R' D R2 U' R2 U' R2 U2 R2 U' D' R U' R'`,
    `R U R' U R U' R' U' L' U2 R U2' R' U2 L`,
    `F U' R' U2 R U F' R' U' R U R' U R`,
    `U L' U2 R U2' R' U2 L U R U R' U' R U' R'`,
    `U R U R' U B' U R U' R' U' B R U' R'`,
    `R' U2 R' D' R U2 R' D R' U R' U R U2 R'`,
    `U R' U' R U' F U' R' U R U F' R' U R`,
    `U2 R U2 R D R' U2 R D' R U' R U' R' U2 R`,
    `U' l' U2 R' D2 R U2 R' D2 R2 x'`,
    `U' l U2 R D2 R' U2 R D2 R2 x`,
    `U2 F R U R' U' R U' R' U' R U R' F'`,
    `U2 R U2 R2 U' R2 U' R' U2 R' U R L' U R' U' R L`,
    `U R' U' R' D' R U R' D R U' R U' R' U2 R`,
    `U R U R D R' U' R D' R' U R' U R U2 R'`,
    `L' U' L U' R U2 R' U' R U2 L' U M' x'`,
    `L U' R U' L' U R2 U2 L U' L' U2 R`,
    `R2 U' R2 U' R' D R' U R D' R' U R2`,
    `R' U D' R U2 R' D R' U' R U2 R' U' R2`,
    `U R U' R2' D' r U2 r' D R2 U' R' U' R U' R'`,
    `R2 U R' D' R U R' D R' U' R2 U' R2`,
    `U2 r2 U R' U' r' F R F' U R' U' r' F R F'`,
    `U2 R2 F R U R' U' R' F' R' U' R2 U2 R U2 R`,
    `U2 R U' R2 D' r U2 r' D R2 U R'`,
    `R' U R2 D r' U2 r D' R2 U' R`,
    `U2 R2 U' R D R' U' R D' R U R2 U R2`,
    `U R2' F R U R U' R' F R U2' R' U2 R' F2 R2`,
    `U L' U' L R U2 L' U' L U' R' U R U2 R'`,
    `U2 R U R' F' R U R' U' R' F R U' R' F R U R U' R' F'`,
    `U2 R U' R' U2 R U R' U2 R U R' U R U' R'`,
    `U' R U R' U R U2 R' U' R U2 R' U' R U' R'`,
    `U' R U R' U R U' R' U R' U' R2' U' R2 U2 R`,
    `R U2 R' U' R U' R' U R U R' U R U2 R'`,
    `U' R' U' R U' R' U R U' R U R2' U R2 U2 R'`,
    `U2 R' U2 R U R' U R U' R' U' R U' R' U2 R`,
    `U' R' U' R2 U R2 U R2 U2 R' U R' U R`,
    `U' R U R2 U' R2 U' R2 U2 R U' R U' R'`,
    `R U2 R' U' R U' R2 U2 R U R' U R`,
    `U2 R' U2 R U R' U R2 U2 R' U' R U' R'`,
    `R' U R U2 R' U' R U' R U R' U' R' U' R U R U' R'`,
    `U' R U R' U R U2 R' U2 R' U' R U' R' U2 R`,
    `R' U' R U' R' U2 R2 U' L' U R' U' L`,
    `U' R U2 R D R' U2 R D' R' U2 R' U' R U' R'`,
    `U2 R2 D r' U2 r D' R' U2 R'`,
    `U R2 D R' U R D' R2 U R U2 R'`,
    `U' R U2 R2 D' R U2 R' D R2 U' R' U2 R U2 R'`,
    `U2 R2 D R' U2 R D' R' U2 R'`,
    `R U R' y' R' U' R2 u R' U R' U' R u' R'`,
    `U2 R' U R D' R U R' D R2 U' R U R U2 R`,
    `U R' U' L U' R U L' U R' U' R U' R' U R`,
    `U R' U R' U' D' R U' R' U2 R U' R' D R U' R`,
    `U' R' U' R U' L U' R' U2 L' U2 R U' L U2 L'`,
    `U' R U' R' U R U R' U' R U R' U' R U L U' R' U L'`,
    `R2' D' r U2 r' D R U2 R`,
    `U R2' D' R U' R' D R2 U' R' U2 R`,
    `U2 R U R' U R U2 R2 U L U' R U L'`,
    `R' U L U' R U L' R U R' U R U2 R'`,
    `R2 D' R U2 R' D R U2 R`,
    `U R' U R U2 L' R U' L U R2 U2 L' U2 L R`,
    `U R U R' U' L' U2 R U L U R' U L' U L`,
    `R U' R' D R' U' R D' R2 U R' U' R' U2 R'`,
    `R' U2 F U F' R F U2 R' U' R U F'`,
    `U' L U R' U L' U' R U' L U L' U L U' L'`,
    `R2' F2 R2 U R2' F2 R2 U' R2' U' R F2' R' U R F2' R`,
    `U' R U R' U2 F2 R U2 R' U2 R' F2 R2 U R'`,
    `R' F R U' R' U' R U R' F' R U R' U' R' F R F' R`,
    `L' R' U2 L U2 R U' L' U R' U R U' L`,
    `U' F2 R U' R' U' R U R' F' R U R' U' R' F R F2`,
    `U R U' L U L' U R' U' l U2 R U2 R2 x`,
    `U' F U R2 D' R U' R' D R2 F' R' U R`,
    `U' R' U' R F R2 D' R U R' D R2 U' F'`,
    `L U R' U L' U2 R U' R' L U L' U2 R`,
    `R U' R' U R U' L U L' U x' U2 R U2 R2 x`,
    `U F U R U2' R' U R U R2' F' r U R U' r'`,
    `U2 F R2 U R' D R2 D' R U' R2' F' R U' R'`,
    `U' r U R' U' r' F R2 U' R' U' R U2 R' U' F'`,
    `U2 R U R' F R2 U R' D R2 D' R U' R2' F'`,
    `L U L' U' R' U2 L U L' U2 L R U' L'`,
    `U' R U2 R' U' R U' R D' R U2 R' D R U2 R`,
    `R' U' R U L U2 R' U' L' U' L R U2 L'`,
    `U2 R2 F2 R U2 R U R2 F2 R2 U R' F2 R`,
    `x' R2 D2 R' U2 R D2 R' U2 R' x`,
    `U2 x R2 D2 R U2 R' D2 R U2 R x'`,
    `F R U' R' U R U R' U R U' R' F'`,
    `U2 R U' R2' F R U R U' R2' F' R U' F' U F`,
    `U' R' U2 R U2 L' U L U2 R' U R U' L' U L`,
    `U L U2 L' U2 R U' R' U2 L U' L' U R U' R'`,
    `R' U2 R U R' U R' D' R U' R' D R U R`,
    `R U R' F' R U R' F' R U R' U' R' F R2 U' R' F R U' R'`,
    `R U' R' U' R U R D R' U R D' R2`,
    `R U' L' U R2 U' R U' L U R' U2 L' U2 L R`,
    `R U R' U L' U R U' M' x' U' R U' R'`,
    `R' U2 R F U' R' U' R U F'`,
    `F R U' R' U' R U2 R' U' R U' R' U' R U2 R' U' F'`,
    `U' r U R' U' M U R U' R' F R U R' U' F'`,
    `U L U2 L' R' U L U' L' R U' L U' L'`,
    `U R U L' R' U2 R U M' x' z R U' R U z'`,
    `L U2 L' F' U L U L' U' F`,
    `M U' M' F R U R' U' F' M U M'`,
    `L U2 R' U R U2 L' U' R' U2 R`,
    `U2 M' U R' U2' R U R' U R2 z x' U R U' R' F'`,
    `U2 R U R' U R U2 R' U R U2 R' U' R U' R'`,
    `U' R U R' U' R U' R' U2 R U' R' U2 R U R'`,
    `U R U2 R' U' R U' R' U' R U R' U R U2 R'`,
    `U R' U2' R2 U R2' U R U' R U R' U' R U' R'`,
    `U R' U2 R U R' U R U R' U' R U' R' U2 R`,
    `U R U2 R2 U' R2 U' R' U R' U' R U R' U R`,
    `U2 R U R' U R' U2 R2 U R2 U R2 U' R'`,
    `R' U' R U' R U2 R2 U' R2 U' R2 U R`,
    `R' U' R U' R' U2 R2 U R' U R U2 R'`,
    `U2 R U R' U R U2 R2 U' R U' R' U2 R`,
    `R U R' U' R U' R U2 R2 U' R U R' U' R2 U' R2`,
    `U R U2 R' U' R U' R' U2 R' U2 R U R' U R`,
    `R' F R' U F' R' F U' R2 F' R U R'`,
    `U' L U' R' U L' U' R2 U2 R' U' R U' R'`,
    `U' R' U2 R U R2' D' R U R' D R2`,
    `R' U2 R' D' r U2 r' D R2`,
    `U' R' D' L U' D R' D R U R' D2 L' D R2`,
    `R' U2 R' D' R U2 R' D R2`,
    `U' L' U R' U' R U L U2 R' U' L' U' R U' L`,
    `U R U2 R' F U2 F' U' R F U' F' U2 R'`,
    `R2 U' R' U' R2 U R U D' R U2 R' D R2`,
    `U' L2 D' R' B2 R' D2 L' D R2 D2 L'`,
    `U' R' U' D R' U2 R U2 D' R2 U2 R' U' R2 U' R'`,
    `U' R U' R2 F2 R U2 R U2 R' F2 U2 R U' R'`,
    `L F' U L U' L' U' F L U2 L' U2 L'`,
    `R2' U R2 U' R' U' F R2' U R2 U' F' R'`,
    `L U' L' U2 L R U' L' U' R' U' R U' R'`,
    `L U' R U L' U R U2 R U' R U R' U2 R2`,
    `U' R U2 R2 U L U' L' R U2 R U L U2 L' R'`,
    `x' R U' R' D R U R' D' x`,
    `U' R' U2 R U2 D' R U' R U R U' R2 D`,
    `R F U' R' U R U R' U R U' F' R'`,
    `U' U M' U2 y R' U2 R U2 F l U' z'`,
    `R U R' U R U' R' U' L' U R U' M' x'`,
    `U' x' M' U L' U2 R U2 L U' L' U' R' U R`,
    `U' R' F' R U R' U' R' F R U' R U R' U R`,
    `U' R' U' R U R' F2 R U2 R' U2 R' F2 R2`,
    `U' R' U L' U' L R U2 L' U L U L' U L`,
    `R U R' U2 L U' R U' R' U R U2' R' L'`,
    `U' R' U L' U' R U' L' U2 L' U L' U' L U2 L2`,
    `U' x' D R U R' D' R U' l'`,
    `U' R U L' U R' U' L U' R U R' U2 R U2 R'`,
    `U R' L' U R U' R' L U' R U' R' U R`,
    `U2 R D' U R2 U R' U' R' U R' U2 D R'`,
    `U2 R U2 R' U' R U R D R' U' R D' R' U' R'`,
    `U' L' U' L U' L' U L U R U' L' U M' x'`,
    `U' M' U2 y' L U2 L' U2 F' r' U z`,
    `U' F R U' R' U' R U2 R' U' F'`,
    `U2 R U R' U R U2' R D R' U2 R D' R' U2 R'`,
    `L U2 L' U' L2 D L' U' L D' L2`,
    `U' R U' R' F2 U2 F2 D R' U R U' R D'`,
    `U R U2 R D r' U2 r D' R2`,
    `U R U2 R D R' U2 R D' R2`,
    `U R U2' R' U2 R U R2' D' R U2 R' D R2 U2' R'`,
    `R' U2 R' U' R' U R2 D' R U' R' D R' U' R`,
    `U' R U R' F' U' R' U2 R U F R' U R2 U2 R'`,
    `L U D' L U2 L' U2 D L2 U2 L U L2 U L`,
    `R2 D' R2 U R' D R2 U' D r2 D2 r2 D' R'`,
    `U R' U F U' F' U2 R F R' U R U2 F'`,
    `L' U L2 F2 L' U2 L' U2 L F2 U2 L' U L`,
    `U2 R' F2 R2 U' L' U R2 r U2 R x'`,
    `R U2 R' U' L' U2 R U M' x' U L' U L`,
    `U' L' U2 L U R U2 L' U' M' x' U' R U' R'`,
    `U' R' F2 R2 L' U' L U R2 F2 R`,
    `U R U' R F' R' U R F' R2 F U' F' R2 F2 R2`,
    `U' R' U L2 D' L' U2 L D L' U R U L'`,
    `U' F R U R' U' R' F R2 U' R' U' R U R' F2`,
    `U' R' U' R U R' U' R' F R2 U' R' U' R U R' F' U R`,
    `U' R' U' R U R' F' R U R' U' R' F R2`,
    `F R U R' U' R U' R' U2 R U2 R' U' F'`,
    `U' L' U2 R U' R' U2 L R U' R'`,
    `U' F R U' R' U' R U R D R' U' R D' R' U2 R' U' F'`,
    `U' R U2 R' U2 R' U2 R' U R U' R U2 R2 U2 R'`,
    `U R U2 R' U' R U' R' U R' U2 R U R' U R`,
    `U R U R' U R U2 R' U R' U' R U' R' U2 R`,
    `U R2 U' R U R U' R' U' R U' R' U R' U R2`,
    `R' U2 R U R' U R U' R U2 R' U' R U' R'`,
    `U2 R2 U' R U' R U R' U R U R' U' R' U R2`,
    `R' U' R U' R' U2 R U' R U R' U R U2 R'`,
    `R2 U R' U' R' U R U R' U R U' R U' R2`,
    `R' U2 R U R' U R U2 R' U' R U' R' U2 R`,
    `R' U' R U' R' U2 R U2 R' U2 R U R' U R`,
    `U' R U R' U R U' R' U R U' R' U R U2 R'`,
    `R U' R' L' U2 L U L' U L R U2 R'`,
    `R' U2 R U' L U2 R' U' R U R' U R L'`,
    `R U2 R' U L' U2 R U R' U' R U' R' L`,
    `U R U R' U R' D R2 U' R' U R U' R D' R' U' R'`,
    `U' R' U' F U' R2 U R2 U F' R2 U2 R'`,
    `U L U2 R' L' U L U2 R U2 L' U R' U2 R`,
    `U' R U L' R' U2 R U2' R' U2 L U' R U2' R'`,
    `R2' F R U R U' R' F' R U' R' U' R U R' U R`,
    `U F U R U' R' U R U2 R' U' R U R' F'`,
    `U' R U R' U R U' R' U' R' F' R U2 R U2' R' F`,
    `U' F U' R U' R' U R U R' U2 R U2 R' U F'`,
    `U R2 D' R U' R' D R U R' D' R U R' D R U R U' R' U' R`,
    `R' U' F' R U R' U' R' F R2 U2' R' U2 R`,
    `L' U L U' L' U L U L' U2 R' U L U' R`,
    `U2 R U' R' U R U' R' U' R U2 L U' R' U L'`,
    `R' U2 R' D R' U R D' R U R2 U2 R'`,
    `R U2 R D' R U' R' D R' U' R2 U2 R`,
    `R U R' U R' U' R2 U2 L' U R2 U' L U' R`,
    `R U' L' U R' U L2 U L2 U L U' L U' L'`,
    `U R U2 R2 U' R2 U' R D' r U2 r' D R2`,
    `R2 U R' U' R' U2 R' U2 R U R' D R' U R D'`,
    `U2 L' U R U' L U' R' U' R U' R'`,
    `L' U L U2 R' L' U L2 U' R U L'`,
    `L U' L' U2 R L U' L2 U R' U' L`,
    `R U' r' F R' F r U r' F r`,
    `R' U2 R U R' U' R U2 L U' R' U R L'`,
    `R U' R' U' R U' R' U R U R' U R' F' R U R U' R' F`,
    `U L' R U R' U' L U2 R U' R' U R U2 R'`,
    `U2 R' U2' R U R' U' R U R2' F R U R U' R' F' R`,
    `L' U2 R U' L U' R' U' R U2 L' U M' x'`,
    `U' R U' R U2 R U2 R2 U R' F2 R' U R' U' R2 F2`,
    `U2 R U R' U R U R' U x U' L U' L' U2 R' U R U' x'`,
    `U' R U R' U R U' R' U F2 r U2 r' U' r' F r`,
    `U R' U' R U' B2 R' U2 R U2 l U2 l'`,
    `U' R' U' R U' R' U R U' R' U R' D' R U R' D R2`,
    `U R U2 R' U' R U' R2 U L U' R U L'`,
    `R' F2 R U2 R U2 R' F2 U' R U' R'`,
    `R' F R U R' U' R' F' R2 U' R' U R U' R' U2 R`,
    `R U2 R' U' R U R' U2 L' U R U' M' x'`,
    `L R' U2' R2 U R2' U R U L' U' R U2 R'`,
    `U' L R' U' R U L' U2 R' U R U' R' U2 R`,
    `R U R' U' R' F R2 U R' U' R U R' U' F'`,
    `U2 R U2 R' U2' R' F R2 U' R' U2 R U2' R' U' F'`,
    `U' R U R' U R2 F2 U R U R2 U' R' U' F2 R2`,
    `r' F' r U r U2' r' F2 U' R U R' U' R U' R'`,
    `l U2 l' U2 R' U2' R B2 U R' U R`,
    `U' R' U2 R U R' U R2 U' L' U R' U' L`,
    `U' R' F2 R U' R2 F2 R U R U R2 F2 R2`,
    `U' R U R' U F2 R U2 R' U2 R' F2 R`,
    `R U D' R U R' D R2 U' R' U' R2 U2 R`,
    `U' R U R' F' R U R' U R U2 R' F U R U2 R'`,
    `U2 F R2 U' R U2 R U R' U R' U R2 F'`,
    `U R U R' U' R U R2 D' R U' R' D R U' R U2 R'`,
    `F U R' U' R2 U' R2 U2 R U2 R U R' F'`,
    `U' R U R' U L' U R U' L U' R' U R U2 R'`,
    `R' L U L' U L U R U L' U R' U R`,
    `L U L' U R' U L U R U R' U M x`,
    `U2 R U2 R' U R' D' R U R' D R2 U' R' U R U' R'`,
    `F R2 U' R U' R U' R' U2 R' U R2 F'`,
    `U' R' U' R U R' U' R2 D R' U R D' R' U R' U2 R`,
    `U R U2 R' U' F' R U2 R' U' R U' R' F R U' R'`,
    `R U2 R2 U' R2 U' R2 U2 R`,
    `U R U R' U R U2' R2' U2' R U R' U R`,
    `U' R U2 R' U2 R U' R' U2 R U' R' U2 R U R'`,
    `U R' U2 R U2 R' U R U2 R' U R U2 R' U' R`,
    `U2 R U' R' U2 R U R' U2' R U R' U2' R U2 R'`,
    `U2 R' U R U2' R' U' R U2' R' U' R U2' R' U2 R`,
    `U' R' U' R U' R' U2 R2 U2 R' U' R U' R'`,
    `R' U2 R2 U R2 U R2 U2 R'`,
    `R U R' U R U2' R' U' R U R' U R U2' R'`,
    `R U R' U' R' U2 R U R' U R2 U2 R'`,
    `U R U R' U R U2 R' U R U R' U R U2 R'`,
    `R U R2 U' R2 U' R2 U2 R2 U' R' U R U2 R'`,
    `L' U2 L U2 R U' L' U M' x'`,
    `U R U2 R D R' U' R D' R2 U R U2 R'`,
    `U L' U R U' L U' R2 U' R2 U' R2 U2 R`,
    `U L' R U2 R2 U' R2 U' R2 U' L U' R`,
    `L' R U R' U' L U R U2 L' U R' U' L`,
    `U' R' U' R U' R B' U R2 U R2 U' B U' R'`,
    `U R' U' F R U R' U' R' F U' R F2 R' U F2 R2`,
    `U2 F R U R2 U' R2 U' R2 U2 R U R U R' F'`,
    `U' R' U2 R' D R' U R D' R' U' R' U R' U R`,
    `U2 R U R' U R2 D R' U2 R D' R2`,
    `F R' U' R2 U' R2 U2 R2 U' R' F'`,
    `R U R' U' L U' R U L' U' R' U' R U2 R'`,
    `R U' R F2 R' U2 R' U R U2 R' U R2 F2 R2`,
    `U L' U2 L U' R U' L2 U R' U' L2 U' L' U L`,
    `U R' U' F2 U' R2 U R2 U F2 R2 U2 R'`,
    `U2 R U2 R' U L' U2 R U R' U2 L U R U' R'`,
    `U R U2 L' R' U2 R U R' U2 L R U2 R'`,
    `R2' F2 r U R2 U' r' F R2 F R2'`,
    `U2 R U R' U' R' U' F2 U R F2 R' F2 R F2 U' F2`,
    `U L' U' L U' R U2 L' U' R' U2 L U' R U' R'`,
    `U R' B2 R U R U R' U2 R U R2 B2 R`,
    `U R D' R2 U' F2 U' F2 R U2 R2 D R2`,
    `U' R U R' U R U' R D R' U' R D' R2`,
    `U2 R2 D' R U' R' D R U' R U R' U R`,
    `R U R' U' F' L' U2 L U x U2 R' U' l`,
    `U' R' U2 F' R U R' U' R' F R U2 R`,
    `R' U2 R L U2 R' U L' U' L U' R U2 L'`,
    `L U2 L F L' U' L' U L F' U2 L'`,
    `R U' L' U R' U' L`,
    `U' R' U2 R2 U R D' R U R' D R2 U' R U' R'`,
    `L' U' L U' L' U' R U' L U' R' U' R U' R'`,
    `U' R2 U R U' R2 U' R U R' D R' U R D'`,
    `R' L' U2 R L2 U' R' U L2 U2 R U' L`,
    `R U' L' U R' L' U' L' U' L' U L U L2`,
    `R2' U R U R' U' R' U' R' L' U R' U' L`,
    `U' R' U' D R' U R U2 D' R2 U R' U' R'`,
    `L' R U R' U' L U2 R U2 R'`,
    `U' L' U L U2 R U' L' U R2 U L U' R`,
    `U R' U2 R U R2 D' R U' R' D R U2 R`,
    `R U R' F' R U R' U' R' F R2 U' R' U' R U R' U R U2' R'`,
    `U R U' L' U R' U2 L U R U' L' U M' x'`,
    `U F R' U' R2 U' R2 U2 F R F' R U' R' F'`,
    `U2 L U2 L' U R' U2 L U' L' R U R' U R`,
    `U' R' U' L U' R2 U L' R U' R2 U2 R' U' R2`,
    `U L U2 L' U2 R' U L U' L' R2 U2 R' U' R U' R'`,
    `U R U' L U' R2 D' F2 D R2 U2 L' R'`,
    `U z F' U' R' U2 R2 U2 R' U2 R' U' F z'`,
    `U2 R2 D' R U2 R' D R2 U R' U R`,
    `U2 R' U' L U' R' U L' U R' U R' U' R U2 R2`,
    `U' F' L' U' L U L' U' L F' L F L' U F`,
    `U L' R' U2 L U R U2 L U' R' U L2 U' L U' R`,
    `U' R2 U2 R U' R' U R' U L' U R' U' L U' l' x'`,
    `U' R U' L' U R' U' R U' L U R' U' L' U L`,
    `F R U R' U R U2 R U2 R2 U' R2 U' R2 F'`,
    `U R' U2 R U R' U' R L U' R' U L' U2 R`,
    `U' R U2 L' U R' U' R L U' R' U R U2 R'`,
    `U2 R U R' U L' U R U' L U2 R'`,
    `U' R U' L U' L2 U R' U' R L2 U L' U R'`,
    `R' U2 L U' R U L' U R' U R`,
    `F R U' R2 U2 R U R' U R2 U R' F'`,
    `U2 R U' R' U' R U2 R' U2 R U R' U2 R U R'`,
    `U' R2 U' R2 U' R U2 R U' R' U' R U R2`,
    `R U R2 U' R2 U' R2 U2 R2 U2 R'`,
    `U' R' U2 R U R' U R`,
    `U' R2 U R' U' R' U' R U2 R' U' R2 U' R2`,
    `U' R2 U R U' R' U' R U2 R U' R2 U' R2`,
    `R U R' U R U2 R'`,
    `R' U2 R2 U2 R2 U' R2 U' R2 U R`,
    `R U R' U R2 U R U R2 U' R' U' R2`,
    `U' R' U2 R2 U R U R U' R' U' R2 U R`,
    `U2 R' U' R U' R U R2 U R2 U2 R'`,
    `R U R' U R' D' R L F2 L' U2 R2 D R2`,
    `U' R U R' U' L' U2 R U' R' U2 L U' R U2 R'`,
    `R U2' R2' F2 U' R2 U' R2' U F2 U R`,
    `R' U' R U R2 U L U' R2 U L' U R' U2 R`,
    `F2 R2 u' L F2 L' u R2 F U2 F`,
    `U2 R' F U2 F' R F R' U2 R F'`,
    `R' U L U' R2 z' R2 U' L U R2 U' D' z`,
    `U R' F R' F' R' U2 R' U2 R2 U2 R U2 F R2 F'`,
    `U R U R' U L' U2 R U L U2 R' U L' U L`,
    `U R U R' U2 L' U2 R U2 L U L' R' U2 L`,
    `U R' U L U' R U' R' L' U L U' R U2 L'`,
    `U2 R2 D R' U R D' R' U R' U' R U' R'`,
    `U R' U' R U' R' U R' D' R U R' D R2`,
    `U' L U' R' U L' U R2 U R2 U R2 U2 R'`,
    `U R U2 R' U' F' R U R' U' R' F R2 U' R'`,
    `U2 R U2' R' U2 L' U R U' M' x'`,
    `R' U' R U' R' U' L' U2 R U' R' U2 R L`,
    `U R U R' U R' F U' R2 U' R2 U F' U R`,
    `R' L U' R U L' U' R' U2 L U' R U L'`,
    `R U' L U2 R' U R U2 R' U2 L' U' L U' L'`,
    `U2 R' U' R U' R2 D' r U2 r' D R2`,
    `U2 R' U' R U' R2 D' R U2 R' D R2`,
    `U L U L' U L U2 L2 R U R' U' L U2 R U2 R'`,
    `U R' U' R U' R' U y' R' U2 R U' R' U' R B`,
    `U L U2 L' U2 R' U L2 U' R U L' U' L'`,
    `U' R U2 R' U' R U R D R' U2 R D' R2`,
    `U2 R' U2 R' F' R U R U' R' F U2 R`,
    `U2 L' U' L U F R U2 R' U' x U2 L U r'`,
    `U R U2 R D R2 U' R U' R' U2 R2 D' R2`,
    `U' L U2 L2 U' L' D L' U' L D' L2 U L' U L`,
    `R' U L U' R U L'`,
    `U2 R U R' U R U L' U R' U L U L' U L`,
    `U R2 U' R' U R2 U R' U' R D' R U' R' D`,
    `U2 L' U R U' L R U R U R U' R' U' R2`,
    `U R U2 R' U' R U2 R F2 R' U R' U' R2 F2 R2`,
    `U' L U D' L U' L' U2 D L2 U' L U L`,
    `U2 R' U' R F2 R' U R2 U2 R' U R U R' F2`,
    `L R U2 R' U' R U2 L' U' R' U' R U' R'`,
    `U' R' U L' U R2 U R2 U R2 U2 R' L`,
    `x' M' U' R U L' U2 R' U2 R`,
    `U' R U' R' U2 L' U R U' L2 U' R' U L'`,
    `U R U R' U R' U' R' D R' U' R D' R U2 R`,
    `U L' U R U' L U2 R' U' L' U R U' L R'`,
    `U2 R2 D r' U2 r D' R2 U' R U' R'`,
    `R' U' R U' R' U2 L' U2 L U L' U2 R U' L`,
    `R U2 R' U R U L U' R' U L' U R U' R'`,
    `U' R' U' R U R U' R' U2 R L U' R2 U L' U2 R`,
    `U2 R2 D R' U2 R D' R2 U' R U' R'`,
    `U F R U R2 U2 R2 U R2 U R F'`,
    `R U2 L' U R' U' L U' R U' R'`,
    `U' R U2 R2 U' R2 U' R' F U' R' U' R U F'`,
    `U2 F R U' R2 U' R U' R' U2 R2 U R' F'`,
    `L' U' L U' R U' L' U R' U2 L`,
    `U2 R' U' R2 U' L U2 R' U R U2 R2 L' U2 R`,
    `R U2 R' U' R U L' U L U2 R' U' L' U2 L`,
    `U R' U2 L U' R U L' R' U R U' R' U2 R`,
    `U' R U2 R' U' R U R' L' U R U' L U2 R'`,
    `U R U R' U L' U2 R U2 L U2 L' R' U2 L`,
    `U' F R U R' U' R U R' F R' F' R U' F'`,
    `U2 R U L' U R U' L U' R U' R U R' U2 R2`,
    `U L R U2 R' U' L' U2 R' U L U' R2 U R' U L'`,
    `U' R2 U' R U' R2 U R2 U' R' U R2 U R2`,
    `U R2 U R2 U R U2 R' U R U R U' R2`,
    `U' R2 F2 R' U2 R' U' R U' R F2 R2`,
    `U R2 U' R' U R U R' U2 R' U R2 U R2`,
    `R' U' R2 U R2 U R2 U2 R2 U2 R`,
    `U R U2 R' U' R U' R'`,
    `R U2 R2 U2 R2 U R2 U R2 U' R'`,
    `R' U' R U' R' U2 R`,
    `U R U2 R2 U' R' U' R' U R U R2 U' R'`,
    `R' U' R U' R2 U' R' U' R2 U R U R2`,
    `U2 R U R' U R' U' R2 U' R2 U2 R`,
    `U R U' R2 U' R U' R' U2 R' U2 R' U' R U' R2`,
    `x' M' U' R U' R' U R U2 L' U R' U2 R`,
    `R' L U L' U L U' L' U2 R U' L U2 L'`,
    `U L' U2 L2 F' U L2 U L2 U' F U' L'`,
    `U' R U2' R2' F U' R2 U' R2' U F' U R`,
    `U' R B' R' B U2 R2 F' r U' r' F2 R2`,
    `U' R U' R2' F2 R U2 R U2' R' F2 U' R U2 R'`,
    `U' F R U R' U' R' F' U2 R U R' U R2 U2 R'`,
    `U2 F R U' R' U R U2 R' U' R U R' U' F'`,
    `R' F R U R' U' F' R U' R' U R' F R F' U R`,
    `U' R' U2 R U2' R2 F' R U R U' R' F U R`,
    `F B' R2 B R2 U' R2 U' R2 U R2 F'`,
    `F U' R U2 R' U2 R U' R' U' R U R' U F'`,
    `U2 R2 D R' U R D' R2' U R2 D R' U2 R D' R2'`,
    `U R' U2 R2 U R D' R U R' D R' U2 R'`,
    `U2 R2 D' R U' R' D R2 U' R2 D' R U2 R' D R2`,
    `U' R U2 R2 U' R' D R' U' R D' R U2 R`,
    `U2 R U R' U R' U' R2 U' R2 U' L U' R U L'`,
    `U2 R' U' R U' R U R2 U R2 U L' U R' U' L`,
    `D R' U' R D' R U' R' U2 R U2 R U R U' R2`,
    `U R U R' U R U2 R' F R U' R' U' R U2 R' U' F'`,
    `R' U' R U' R' U' L U' R U L'`,
    `R U R' U R U L' U R' U' L`,
    `U R' F R' F' R2 U' r' U r U' r' U' r`,
    `U' l U' R U R' l' U r U' r' U r U r'`,
    `F U' R2 U R U2 R' U R2 U2 R' U' R F'`,
    `U' R U R' U R U2 R' L' U2 R U' R' U2 L R U' R'`,
    `U F R U R' U' R U R' U' R U R' U' F'`,
    `x' U' R U' R' U R' F2 R U' R U R' U x`,
    `R U R' U R U2 R2 U2 L U' R U L' U R' U R`,
    `R' U' R U' R' U2 R2 U2 L' U R' U' L U' R U' R'`,
    `U' R' U' R U' R' U2 R U R' U' R L U2 R' U' R U2 L'`,
    `U' R U R' U y' R' U R U' R2 F R F' R`,
    `R U R' U R U' R' U R U2 R'`,
    `R' U' R U' R' U R U' R' U2 R`,
    `U' R' U2 R U R' U' R U R' U R`,
    `U' R U2 R' U' R U R' U' R U' R'`,
    `U' R' U2 R U R' U R U R U R' U R U2 R'`,
    `U R U2 R' U' R U' R' U' R' U' R U' R' U2 R`,
    `U2 R' U' R U' R' U2 R U R U2 R' U' R U' R'`,
    `R' F R U R' F R U' R' F' R U' R' F R U R' F R U' R' F' R`,
]
export { llmap }
